<?php
use Drupal\taxonomy\Entity\Term;
use Drupal\node\Entity\Node;

echo "=== Creating Cat Breed Content ===\n\n";

$breeds = [
    ['name' => 'Ragdoll', 'origin' => 'United States', 'weight' => '12-20 lbs', 'lifespan' => '12-17 years', 'coat' => 'long', 'size' => 'large', 'traits' => ['Calm', 'Affectionate', 'Social'], 'desc' => "The Ragdoll is a large, affectionate cat breed known for its docile temperament and tendency to go limp when picked up. These beautiful cats have striking blue eyes and semi-long silky coats.\n\nRagdolls are known for their gentle and calm nature, making them excellent companions for families. They are not particularly active cats and prefer lounging around the house.\n\nDespite their fluffy appearance, Ragdolls have relatively low-maintenance coats that do not mat easily. They are intelligent cats that can learn tricks."],
    ['name' => 'Persian', 'origin' => 'Iran', 'weight' => '9-14 lbs', 'lifespan' => '14-15 years', 'coat' => 'long', 'size' => 'medium', 'traits' => ['Calm', 'Affectionate', 'Independent'], 'desc' => "The Persian cat is one of the oldest and most popular cat breeds in the world. With their distinctive flat faces and luxurious long coats, Persians are the epitome of feline elegance.\n\nPersians are known for their quiet, sweet temperament. They prefer a calm environment and are not as playful as some other breeds.\n\nTheir beautiful coats require daily grooming to prevent mats and tangles."],
    ['name' => 'Maine Coon', 'origin' => 'United States', 'weight' => '12-18 lbs', 'lifespan' => '12-15 years', 'coat' => 'long', 'size' => 'large', 'traits' => ['Intelligent', 'Playful', 'Social'], 'desc' => "The Maine Coon is one of the largest domesticated cat breeds and is often called the gentle giant. Native to Maine, these impressive cats have adapted to cold climates with thick, water-resistant coats.\n\nMaine Coons are known for their friendly, playful personalities. They are highly intelligent and can be trained to play fetch.\n\nThese cats are very social and get along well with children, dogs, and other cats."],
    ['name' => 'British Shorthair', 'origin' => 'United Kingdom', 'weight' => '12-20 lbs', 'lifespan' => '12-17 years', 'coat' => 'short', 'size' => 'large', 'traits' => ['Calm', 'Independent', 'Affectionate'], 'desc' => "The British Shorthair is one of the oldest English cat breeds. These sturdy, round-faced cats are known for their plush, dense coats and their calm, easygoing nature.\n\nBritish Shorthairs come in many colors, but the blue variety is the most popular. Their round eyes and chubby cheeks give them a teddy bear-like appearance.\n\nThese cats are independent and can entertain themselves, making them suitable for working families."],
    ['name' => 'Bengal', 'origin' => 'United States', 'weight' => '6-18 lbs', 'lifespan' => '12-16 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['High Energy', 'Intelligent', 'Playful'], 'desc' => "The Bengal cat is a stunning breed that looks like a miniature leopard. Created by crossing domestic cats with Asian Leopard Cats, Bengals have distinctive spotted coats.\n\nBengals are extremely active and intelligent cats that require lots of mental and physical stimulation. They love to climb, jump, and play.\n\nDespite their wild appearance, Bengals are affectionate and form strong bonds with their families."],
    ['name' => 'Siamese', 'origin' => 'Thailand', 'weight' => '8-15 lbs', 'lifespan' => '12-15 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Vocal', 'Intelligent', 'Social'], 'desc' => "The Siamese is one of the oldest and most recognizable cat breeds, originating from Thailand. These elegant cats are known for their striking blue eyes and pointed coloring.\n\nSiamese cats are famous for their vocal nature. They love to talk to their owners and have a distinctive loud voice.\n\nHighly intelligent and curious, Siamese cats can be trained to perform tricks and walk on a leash."],
    ['name' => 'Sphynx', 'origin' => 'Canada', 'weight' => '6-12 lbs', 'lifespan' => '12-14 years', 'coat' => 'hairless', 'size' => 'medium', 'traits' => ['Affectionate', 'High Energy', 'Social'], 'desc' => "The Sphynx is perhaps the most distinctive cat breed, known for its lack of fur. Despite their appearance, Sphynx cats are incredibly warm and affectionate.\n\nSphynx cats are extremely social and love being the center of attention. They are natural entertainers who crave warmth.\n\nBecause they lack fur, Sphynx cats require regular baths to remove body oils."],
    ['name' => 'Russian Blue', 'origin' => 'Russia', 'weight' => '5-11 lbs', 'lifespan' => '10-16 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Calm', 'Intelligent', 'Independent'], 'desc' => "The Russian Blue is an elegant cat breed known for its stunning silvery-blue coat and bright green eyes. These cats have a gentle, reserved nature.\n\nRussian Blues are intelligent and sensitive cats that form strong bonds with their owners. They can be shy around strangers.\n\nThis breed is known for being somewhat independent and is often considered hypoallergenic."],
    ['name' => 'Abyssinian', 'origin' => 'Egypt', 'weight' => '7-10 lbs', 'lifespan' => '14-15 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['High Energy', 'Intelligent', 'Playful'], 'desc' => "The Abyssinian is one of the oldest known cat breeds, with a wild appearance reminiscent of ancient Egyptian cats. Their distinctive ticked coat gives them a warm, glowing appearance.\n\nAbyssinians are incredibly active and curious cats. They love to climb, explore, and investigate everything.\n\nHighly intelligent, Abyssinians can learn tricks and enjoy puzzle toys."],
    ['name' => 'Norwegian Forest Cat', 'origin' => 'Norway', 'weight' => '8-16 lbs', 'lifespan' => '12-16 years', 'coat' => 'long', 'size' => 'large', 'traits' => ['Intelligent', 'Playful', 'Independent'], 'desc' => "The Norwegian Forest Cat is a large, natural breed that evolved in Scandinavia. These majestic cats have long, water-resistant double coats and tufted ears.\n\nNorwegian Forest Cats are gentle giants with calm, patient temperaments. They are excellent climbers thanks to their strong claws.\n\nThese cats are independent and can entertain themselves but also enjoy interactive play."],
    ['name' => 'Scottish Fold', 'origin' => 'United Kingdom', 'weight' => '5-11 lbs', 'lifespan' => '11-14 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Calm', 'Affectionate', 'Playful'], 'desc' => "The Scottish Fold is instantly recognizable by its unique folded ears that bend forward and downward, giving these cats an owl-like appearance.\n\nScottish Folds are known for their calm, adaptable nature. They are affectionate without being demanding.\n\nThese cats are moderately active and enjoy interactive play."],
    ['name' => 'Devon Rex', 'origin' => 'United Kingdom', 'weight' => '5-10 lbs', 'lifespan' => '10-15 years', 'coat' => 'curly', 'size' => 'small', 'traits' => ['Playful', 'Social', 'High Energy'], 'desc' => "The Devon Rex is often called the pixie cat due to its elfin appearance. With its large ears and short, wavy coat, this breed looks like something from a fairy tale.\n\nDevon Rex cats are incredibly playful and mischievous. They love to clown around and will do almost anything for attention.\n\nThey are often called velcro cats because they like to stick close to their owners."],
    ['name' => 'Siberian', 'origin' => 'Russia', 'weight' => '8-16 lbs', 'lifespan' => '12-15 years', 'coat' => 'long', 'size' => 'large', 'traits' => ['Playful', 'Intelligent', 'Affectionate'], 'desc' => "The Siberian is Russia's native forest cat, a powerful and agile breed that developed naturally in the harsh climate of Siberia.\n\nSiberians are affectionate and devoted cats that form strong bonds with their families. They are playful and athletic.\n\nKnown for their intelligence, Siberians can learn to play fetch and respond to their names."],
    ['name' => 'Burmese', 'origin' => 'Thailand', 'weight' => '6-12 lbs', 'lifespan' => '15-16 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Affectionate', 'Social', 'Intelligent'], 'desc' => "The Burmese is a compact, muscular cat breed that originated in Burma. These cats have short, satiny coats that lie close to the body.\n\nBurmese cats are extremely people-oriented and thrive on human companionship. They are playful and retain their kitten-like energy.\n\nThese cats are vocal but have a softer, sweeter voice than Siamese cats."],
    ['name' => 'Birman', 'origin' => 'France', 'weight' => '6-15 lbs', 'lifespan' => '14-15 years', 'coat' => 'long', 'size' => 'medium', 'traits' => ['Calm', 'Affectionate', 'Social'], 'desc' => "The Birman, also known as the Sacred Cat of Burma, is a striking breed with a colorpoint pattern and distinctive white gloves on all four paws.\n\nBirmans are gentle, affectionate cats that love to be around people. They are patient and tolerant.\n\nThese cats are moderately active and enjoy interactive play."],
    ['name' => 'Oriental Shorthair', 'origin' => 'United States', 'weight' => '5-10 lbs', 'lifespan' => '12-14 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Vocal', 'Intelligent', 'Social'], 'desc' => "The Oriental Shorthair is a sleek, elegant breed that shares the Siamese body type but comes in hundreds of color combinations.\n\nOriental Shorthairs are extremely vocal and will carry on long conversations with their owners. They demand attention.\n\nThese cats form intense bonds with their owners and can become depressed if left alone too much."],
    ['name' => 'Cornish Rex', 'origin' => 'England', 'weight' => '5-9 lbs', 'lifespan' => '11-14 years', 'coat' => 'curly', 'size' => 'small', 'traits' => ['Playful', 'High Energy', 'Intelligent'], 'desc' => "The Cornish Rex is known for its distinctive wavy coat that feels like crushed velvet. Their slender, athletic bodies are built for speed.\n\nCornish Rex cats are extremely playful and energetic. They love to run, jump, and climb.\n\nDespite their delicate appearance, Cornish Rex cats are hardy and healthy."],
    ['name' => 'Exotic Shorthair', 'origin' => 'United States', 'weight' => '7-14 lbs', 'lifespan' => '12-15 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Calm', 'Affectionate', 'Playful'], 'desc' => "The Exotic Shorthair is essentially a short-haired Persian, with the same flat faces and sweet expressions but with a plush, dense coat.\n\nExotic Shorthairs share the Persian's calm, gentle temperament but tend to be slightly more playful and curious.\n\nThese cats are sometimes called the lazy man's Persian because their short coats require minimal grooming."],
    ['name' => 'Tonkinese', 'origin' => 'Canada', 'weight' => '6-12 lbs', 'lifespan' => '14-16 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Playful', 'Intelligent', 'Social'], 'desc' => "The Tonkinese is a blend of Siamese and Burmese, combining the best traits of both breeds. These cats have muscular bodies and beautiful aqua eyes.\n\nTonkinese cats are playful and intelligent, enjoying games and interactive toys. They are social cats.\n\nThese cats crave companionship and do not like to be left alone for long periods."],
    ['name' => 'Bombay', 'origin' => 'United States', 'weight' => '6-11 lbs', 'lifespan' => '12-16 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Affectionate', 'Playful', 'Intelligent'], 'desc' => "The Bombay was created to resemble a miniature black panther. These sleek, jet-black cats have copper or gold eyes that create a stunning contrast.\n\nBombay cats are affectionate and people-oriented. They love to be the center of attention and follow their owners around.\n\nThese cats are moderately active and enjoy interactive play."],
    ['name' => 'American Shorthair', 'origin' => 'United States', 'weight' => '8-15 lbs', 'lifespan' => '15-17 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Calm', 'Playful', 'Independent'], 'desc' => "The American Shorthair is a true American breed, descended from cats that came with European settlers. These hardy cats have muscular bodies.\n\nAmerican Shorthairs are known for their easygoing, friendly nature. They are excellent hunters.\n\nThese cats are healthy and long-lived, with few genetic health issues."],
    ['name' => 'Turkish Angora', 'origin' => 'Turkey', 'weight' => '5-10 lbs', 'lifespan' => '12-18 years', 'coat' => 'long', 'size' => 'small', 'traits' => ['Playful', 'Intelligent', 'Social'], 'desc' => "The Turkish Angora is an ancient natural breed from Turkey, known for its elegant, flowing coat and graceful movements.\n\nTurkish Angoras are playful, intelligent cats that love to be the center of attention. They are athletic and enjoy climbing.\n\nDespite their delicate appearance, Turkish Angoras are strong-willed and determined."],
    ['name' => 'Himalayan', 'origin' => 'United States', 'weight' => '7-12 lbs', 'lifespan' => '9-15 years', 'coat' => 'long', 'size' => 'medium', 'traits' => ['Calm', 'Affectionate', 'Social'], 'desc' => "The Himalayan is a cross between Persian and Siamese cats, combining the Persian's luxurious coat with the Siamese's pointed coloring and blue eyes.\n\nHimalayans are calm, gentle cats that prefer a peaceful environment. They are affectionate and enjoy lap time.\n\nThese cats require daily grooming to maintain their long, silky coats."],
    ['name' => 'Ragamuffin', 'origin' => 'United States', 'weight' => '10-20 lbs', 'lifespan' => '12-16 years', 'coat' => 'long', 'size' => 'large', 'traits' => ['Calm', 'Affectionate', 'Social'], 'desc' => "The Ragamuffin is a large, friendly cat breed related to the Ragdoll. These gentle giants have plush, rabbit-like coats.\n\nRagamuffins are extremely docile and affectionate. They love to be held and will go limp in your arms.\n\nDespite their long coats, Ragamuffins are relatively easy to groom as their fur resists matting."],
    ['name' => 'Savannah', 'origin' => 'United States', 'weight' => '12-25 lbs', 'lifespan' => '12-20 years', 'coat' => 'short', 'size' => 'large', 'traits' => ['High Energy', 'Intelligent', 'Independent'], 'desc' => "The Savannah is a striking hybrid breed created by crossing domestic cats with African Servals. These tall, lean cats have wild-looking spotted coats.\n\nSavannahs are extremely active and intelligent. They need lots of space to run and jump.\n\nThese cats require experienced owners who can provide plenty of stimulation."],
    ['name' => 'Manx', 'origin' => 'Isle of Man', 'weight' => '8-12 lbs', 'lifespan' => '14-16 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Playful', 'Intelligent', 'Social'], 'desc' => "The Manx is famous for its lack of tail, a natural genetic mutation that originated on the Isle of Man. These round, cobby cats have powerful hind legs.\n\nManx cats are playful and intelligent with a dog-like personality. They can be trained to fetch.\n\nManx cats are social and bond strongly with their families."],
    ['name' => 'Chartreux', 'origin' => 'France', 'weight' => '7-16 lbs', 'lifespan' => '11-15 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Calm', 'Intelligent', 'Independent'], 'desc' => "The Chartreux is an ancient French breed known for its distinctive blue-gray coat and copper-colored eyes.\n\nChartreux cats are known for their calm, observant nature. They are intelligent and attentive.\n\nThese cats are independent and can entertain themselves, making them suitable for working families."],
    ['name' => 'Japanese Bobtail', 'origin' => 'Japan', 'weight' => '6-10 lbs', 'lifespan' => '15-18 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Playful', 'Intelligent', 'Vocal'], 'desc' => "The Japanese Bobtail is an ancient breed depicted in Japanese art for centuries. These cats are famous for their short, pom-pom-like tails.\n\nJapanese Bobtails are active, playful cats that love to carry toys and play fetch. They are highly intelligent.\n\nJapanese Bobtails are social cats that get along well with children and other pets."],
    ['name' => 'Korat', 'origin' => 'Thailand', 'weight' => '6-10 lbs', 'lifespan' => '15-20 years', 'coat' => 'short', 'size' => 'small', 'traits' => ['Intelligent', 'Playful', 'Affectionate'], 'desc' => "The Korat is one of the oldest stable cat breeds, originating from Thailand where it is considered a symbol of good luck.\n\nKorats are intelligent, playful cats that form strong bonds with their owners. They are sensitive to their owners' moods.\n\nKorats prefer a quiet, stable environment and are devoted to their families."],
    ['name' => 'Ocicat', 'origin' => 'United States', 'weight' => '6-15 lbs', 'lifespan' => '10-15 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Playful', 'Social', 'Intelligent'], 'desc' => "The Ocicat looks like a wild cat but is entirely domestic. These athletic cats have spotted coats that give them an exotic appearance.\n\nOcicats are extremely social and outgoing. They love people and will greet visitors at the door.\n\nDespite their wild appearance, Ocicats are gentle and affectionate."],
    ['name' => 'Balinese', 'origin' => 'United States', 'weight' => '5-10 lbs', 'lifespan' => '12-20 years', 'coat' => 'long', 'size' => 'medium', 'traits' => ['Vocal', 'Intelligent', 'Playful'], 'desc' => "The Balinese is essentially a long-haired Siamese, with the same striking blue eyes and pointed coloring but with a silky, flowing coat.\n\nBalinese cats are just as vocal and demanding as Siamese. They love to communicate with their owners.\n\nThese cats are intelligent and can be trained to walk on a leash."],
    ['name' => 'Egyptian Mau', 'origin' => 'Egypt', 'weight' => '6-14 lbs', 'lifespan' => '12-15 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Playful', 'Intelligent', 'Independent'], 'desc' => "The Egyptian Mau is one of the few naturally spotted domestic cat breeds. These elegant cats are believed to be descended from ancient Egyptian cats.\n\nEgyptian Maus are the fastest domestic cat breed, capable of running up to 30 mph. They love to play and hunt.\n\nThese cats are loyal to their families but can be shy around strangers."],
    ['name' => 'Somali', 'origin' => 'United States', 'weight' => '6-10 lbs', 'lifespan' => '12-14 years', 'coat' => 'long', 'size' => 'medium', 'traits' => ['High Energy', 'Intelligent', 'Playful'], 'desc' => "The Somali is a long-haired version of the Abyssinian, with the same ticked coat but in a gorgeous flowing length.\n\nSomalis are extremely active and playful cats. They need lots of interactive play and mental stimulation.\n\nThese cats are curious and will investigate everything in their environment."],
    ['name' => 'LaPerm', 'origin' => 'United States', 'weight' => '5-10 lbs', 'lifespan' => '10-15 years', 'coat' => 'curly', 'size' => 'medium', 'traits' => ['Affectionate', 'Playful', 'Social'], 'desc' => "The LaPerm is known for its unique curly coat that can range from wavy to tight ringlets. The breed originated from a natural mutation.\n\nLaPerms are affectionate, gentle cats that enjoy being close to their owners. They are adaptable and easygoing.\n\nDespite their unusual coat, LaPerms are low-maintenance and shed minimally."],
    ['name' => 'Singapura', 'origin' => 'Singapore', 'weight' => '4-8 lbs', 'lifespan' => '11-15 years', 'coat' => 'short', 'size' => 'small', 'traits' => ['Playful', 'Intelligent', 'Affectionate'], 'desc' => "The Singapura is the smallest domestic cat breed, known for its large eyes and sepia-toned ticked coat.\n\nDespite their small size, Singapuras are energetic and playful. They love to climb and perch in high places.\n\nThese cats are affectionate and love to be involved in their owners' activities."],
    ['name' => 'Nebelung', 'origin' => 'United States', 'weight' => '7-15 lbs', 'lifespan' => '11-16 years', 'coat' => 'long', 'size' => 'medium', 'traits' => ['Calm', 'Intelligent', 'Independent'], 'desc' => "The Nebelung is a rare breed that resembles a long-haired Russian Blue. Its name means mist creature in German.\n\nNebelungs are gentle, reserved cats that form strong bonds with their chosen people. They can be shy with strangers.\n\nThese cats are intelligent and can entertain themselves but also enjoy quiet companionship."],
    ['name' => 'Selkirk Rex', 'origin' => 'United States', 'weight' => '6-16 lbs', 'lifespan' => '10-15 years', 'coat' => 'curly', 'size' => 'medium', 'traits' => ['Calm', 'Affectionate', 'Playful'], 'desc' => "The Selkirk Rex has a uniquely curly coat that sets it apart from other Rex breeds. Even their whiskers are curly.\n\nSelkirk Rex cats are patient, tolerant cats that get along well with children and other pets.\n\nThese cats are affectionate without being demanding and enjoy both playtime and relaxation."],
    ['name' => 'Turkish Van', 'origin' => 'Turkey', 'weight' => '7-20 lbs', 'lifespan' => '12-17 years', 'coat' => 'long', 'size' => 'large', 'traits' => ['High Energy', 'Intelligent', 'Playful'], 'desc' => "The Turkish Van is known for its love of water and distinctive van pattern coloring. These cats are natural swimmers.\n\nTurkish Vans are energetic and athletic cats that love to play and climb. They need lots of exercise and stimulation.\n\nThese cats are intelligent and can be trained to play fetch."],
    ['name' => 'Havana Brown', 'origin' => 'England', 'weight' => '6-10 lbs', 'lifespan' => '10-15 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Affectionate', 'Intelligent', 'Playful'], 'desc' => "The Havana Brown is a rare breed known for its rich, chocolate-brown coat and striking green eyes.\n\nHavana Browns are affectionate, people-oriented cats that love to follow their owners around.\n\nThese cats are curious and intelligent, often using their paws to investigate objects."],
    ['name' => 'Burmilla', 'origin' => 'United Kingdom', 'weight' => '6-13 lbs', 'lifespan' => '10-15 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Affectionate', 'Playful', 'Social'], 'desc' => "The Burmilla is a relatively new breed, created by an accidental mating between a Burmese and a Chinchilla Persian.\n\nBurmillas are sweet-natured cats that combine the best traits of their parent breeds.\n\nThese cats are playful and affectionate but not as demanding as some breeds."],
    ['name' => 'Chausie', 'origin' => 'United States', 'weight' => '15-25 lbs', 'lifespan' => '12-14 years', 'coat' => 'short', 'size' => 'large', 'traits' => ['High Energy', 'Intelligent', 'Independent'], 'desc' => "The Chausie is a hybrid breed created by crossing domestic cats with Jungle Cats. These large, athletic cats have a wild appearance.\n\nChausies are extremely active and need lots of space and exercise. They are highly intelligent.\n\nThese cats require experienced owners who understand their need for activity and stimulation."],
    ['name' => 'Snowshoe', 'origin' => 'United States', 'weight' => '7-12 lbs', 'lifespan' => '14-20 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Affectionate', 'Vocal', 'Social'], 'desc' => "The Snowshoe is named for its distinctive white paws. This breed combines the pointed pattern of the Siamese with white markings.\n\nSnowshoes are affectionate cats that love to be with their people. They can be vocal like their Siamese ancestors.\n\nThese cats are intelligent and can learn tricks."],
    ['name' => 'American Curl', 'origin' => 'United States', 'weight' => '5-10 lbs', 'lifespan' => '12-16 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Playful', 'Affectionate', 'Social'], 'desc' => "The American Curl is distinguished by its unique ears that curl backward in an elegant arc. This natural mutation gives them an alert, happy expression.\n\nAmerican Curls are affectionate, people-oriented cats that retain their kitten-like playfulness throughout their lives.\n\nThese cats are adaptable and get along well with children and other pets."],
    ['name' => 'Munchkin', 'origin' => 'United States', 'weight' => '5-9 lbs', 'lifespan' => '12-15 years', 'coat' => 'short', 'size' => 'small', 'traits' => ['Playful', 'Social', 'Affectionate'], 'desc' => "The Munchkin is known for its short legs, caused by a natural genetic mutation. Despite their unique proportions, Munchkins are active and playful.\n\nMunchkins are outgoing, friendly cats that love to play and explore. They are surprisingly fast despite their short legs.\n\nThese cats are social and get along well with other pets and children."],
    ['name' => 'Pixie-Bob', 'origin' => 'United States', 'weight' => '8-17 lbs', 'lifespan' => '13-15 years', 'coat' => 'short', 'size' => 'large', 'traits' => ['Intelligent', 'Playful', 'Social'], 'desc' => "The Pixie-Bob is a muscular, brawny cat with a wild appearance. They often have a bobbed tail and tufted ears.\n\nPixie-Bobs are dog-like in their devotion to their families. They can be trained to walk on a leash and play fetch.\n\nThese cats are social and get along well with children and other pets."],
    ['name' => 'Toyger', 'origin' => 'United States', 'weight' => '7-15 lbs', 'lifespan' => '10-15 years', 'coat' => 'short', 'size' => 'medium', 'traits' => ['Playful', 'Intelligent', 'Affectionate'], 'desc' => "The Toyger was bred to resemble a miniature tiger, with bold stripes and a muscular body. Despite their wild appearance, they are entirely domestic.\n\nToygers are friendly, outgoing cats that enjoy human company. They are intelligent and can be trained.\n\nThese cats are laid-back and adaptable, making them good family pets."],
    ['name' => 'Peterbald', 'origin' => 'Russia', 'weight' => '6-10 lbs', 'lifespan' => '12-15 years', 'coat' => 'hairless', 'size' => 'medium', 'traits' => ['Affectionate', 'Social', 'Intelligent'], 'desc' => "The Peterbald is an elegant hairless breed from Russia. Some Peterbalds have a fine peach-fuzz coat, while others are completely bald.\n\nPeterbalds are extremely affectionate and love to be with their people. They are curious and intelligent.\n\nLike other hairless breeds, Peterbalds need regular bathing and protection from temperature extremes."],
];

echo "--- Creating Breed Terms and Articles ---\n";
$termStorage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
$nodeStorage = \Drupal::entityTypeManager()->getStorage('node');

$charTerms = [];
$allCharTerms = $termStorage->loadByProperties(['vid' => 'cat_characteristics']);
foreach ($allCharTerms as $term) {
    $charTerms[$term->getName()] = $term->id();
}

$count = 0;
foreach ($breeds as $breed) {
    $count++;

    $existing = $termStorage->loadByProperties(['vid' => 'cat_breeds', 'name' => $breed['name']]);
    if (empty($existing)) {
        $breedTerm = Term::create(['vid' => 'cat_breeds', 'name' => $breed['name']]);
        $breedTerm->save();
        $breedTid = $breedTerm->id();
        echo "Created breed term: {$breed['name']}\n";
    } else {
        $breedTid = reset($existing)->id();
    }

    $traitTids = [];
    foreach ($breed['traits'] as $trait) {
        if (isset($charTerms[$trait])) {
            $traitTids[] = ['target_id' => $charTerms[$trait]];
        }
    }

    $node = Node::create([
        'type' => 'cats',
        'title' => $breed['name'],
        'body' => ['value' => $breed['desc'], 'format' => 'basic_html'],
        'field_cat_breed' => ['target_id' => $breedTid],
        'field_characteristics' => $traitTids,
        'field_origin' => $breed['origin'],
        'field_lifespan' => $breed['lifespan'],
        'field_weight' => $breed['weight'],
        'field_coat_type' => $breed['coat'],
        'field_size' => $breed['size'],
        'status' => 1,
        'uid' => 1,
    ]);
    $node->save();
    echo "Created article {$count}: {$breed['name']}\n";
}

echo "\n=== Created {$count} cat articles ===\n";
